(function () {
  "use strict";
  const button=document.getElementById("talk-btn"), status=document.getElementById("talk-status");
  let stream, active=false, peers=new Map(), ice, icePromise;
  async function iceServers(){if(ice)return ice;const backend=window.APP_CONFIG&&window.APP_CONFIG.backendUrl;if(!icePromise)icePromise=fetch(backend+"/api/ice-servers",{cache:"no-store"}).then(response=>{if(!response.ok)throw new Error("ICE configuration is unavailable.");return response.json();}).then(data=>ice=data.iceServers);return icePromise;}
  function set(message){status.textContent=message;button.classList.toggle("talking",active);}
  async function microphone(){if(stream)return stream;if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia)throw new Error("Microphone access is not supported in this browser.");stream=await navigator.mediaDevices.getUserMedia({audio:true});return stream;}
  async function peer(id, offer){let pc=peers.get(id);if(pc)return pc;pc=new RTCPeerConnection({iceServers:await iceServers()});peers.set(id,pc);pc.onicecandidate=e=>e.candidate&&window.roomClient.signal(id,{type:"candidate",candidate:e.candidate});pc.ontrack=e=>{const audio=new Audio();audio.srcObject=e.streams[0];audio.play().catch(()=>{});};(await microphone()).getTracks().forEach(track=>pc.addTrack(track,stream));if(offer){const desc=await pc.createOffer();await pc.setLocalDescription(desc);window.roomClient.signal(id,{type:"offer",sdp:desc});}return pc;}
  async function start(){if(!window.roomClient.isActive()||active)return;window.roomClient.talk("TALK_REQUEST",async result=>{if(!result||!result.ok){set(result&&result.error||"Another member is speaking.");return;}try{await microphone();stream.getAudioTracks().forEach(track=>track.enabled=true);active=true;set("You are speaking");for(const member of window.roomClient.members())if(member.userId!==window.roomClient.userId())await peer(member.userId,true);}catch(e){window.roomClient.talk("TALK_RELEASE");set(e.message||"Microphone permission was denied.");}});}
  function stop(){if(!active)return;active=false;if(stream)stream.getAudioTracks().forEach(track=>track.enabled=false);window.roomClient.talk("TALK_RELEASE");set("Hold to talk");}
  async function signal(message){try{const signal=message.signal;let pc;if(signal.type==="offer"){pc=await peer(message.from,false);await pc.setRemoteDescription(signal.sdp);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);window.roomClient.signal(message.from,{type:"answer",sdp:answer});}else if(signal.type==="answer"){pc=peers.get(message.from);if(pc)await pc.setRemoteDescription(signal.sdp);}else if(signal.type==="candidate"){pc=peers.get(message.from);if(pc)await pc.addIceCandidate(signal.candidate);}}catch(_){set("Voice connection could not be established.");}}
  function floor(speaker, mine){if(!active&&speaker)set(mine?"You are speaking":"A member is speaking");if(!speaker&&!active)set("Hold to talk");}
  ["pointerdown"].forEach(event=>button.addEventListener(event,e=>{e.preventDefault();button.setPointerCapture&&button.setPointerCapture(e.pointerId);start();}));["pointerup","pointercancel","lostpointercapture"].forEach(event=>button.addEventListener(event,e=>{e.preventDefault();stop();}));window.addEventListener("blur",stop);
  window.walkieTalkie={stop:()=>{stop();for(const pc of peers.values())pc.close();peers.clear();if(stream){stream.getTracks().forEach(track=>track.stop());stream=null;}},signal,floor};
})();
